#!/bin/bash

if [[ $(upower -i /org/freedesktop/UPower/devices/battery_BAT1|grep percentage:) ]]; then
    avgwatt=$(cat /var/log/power.log|grep 2D|tail -n 15|awk '{if ($4 >= 3.5) print $4}'|awk '{ total += $0; count++ } END { print total/count }' )
    echo $(echo $(echo $(echo $(upower -i /org/freedesktop/UPower/devices/battery_BAT0|grep energy:|awk '{print $2}')'+'$(upower -i /org/freedesktop/UPower/devices/battery_BAT1|grep energy:|awk '{print $2}')|bc -l)/$avgwatt|bc -l)*60|bc -l)
else
    avgwatt=$(cat /var/log/power.log|grep 1D|tail -n 15|awk '{if ($4 >= 3.5) print $4}'|awk '{ total += $0; count++ } END { print total/count }' )
    echo $(echo $(echo $(upower -i /org/freedesktop/UPower/devices/battery_BAT0|grep energy:|awk '{print $2}')/$avgwatt|bc -l)*60|bc -l)
fi
