#!/bin/bash

if [[ $(upower -i /org/freedesktop/UPower/devices/battery_BAT1|grep percentage:) ]]; then
    bat0p=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0|grep percentage:|awk '{print $2}'|sed 's/%//')
    bat1p=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1|grep percentage:|awk '{print $2}'|sed 's/%//')
    echo $(echo $(echo $bat0p+$bat1p |bc)/2 |bc)
else
    bat0p=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0|grep percentage:|awk '{print $2}'|sed 's/%//')
    echo $bat0p
fi

