#!/bin/bash

bat0s=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0|grep state:|awk '{print $2}')
bat1s=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1|grep state:|awk '{print $2}')

if [[ -n $bat1s ]]; then
    if [[ $bat0s == 'fully-charged' ]] && [[ $bat1s == 'fully-charged' ]]; then
        echo fully-charged
    elif [[ $bat0s == 'charging' ]] || [[ $bat1s == 'charging' ]]; then
        echo charging
    else
        echo discharging
    fi
else
    echo $bat0s
fi
